import { chmod, mkdir, rm, writeFile } from "node:fs/promises";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import type { MatcherOperation, RogatioOperation } from "@rogatio/compiler";
import { compileProject } from "@rogatio/compiler";
import {
  createRequestBodyTrustController,
  defaultTrustInstallRoot,
  normalizeRuntimePreset,
  RUNTIME_LIMITS,
  type RuntimeMockConfig,
  readProviderConfig,
  runNativeHost,
  selectTrustPlatformAdapter,
} from "@rogatio/runtime";
import { validateProjectDetailed } from "@rogatio/schema";
import { showRuntimeHelp } from "../help.js";
import {
  createJsonFileProjectStorage,
  type ProjectStorage,
} from "../utils/file.js";

export interface RuntimeCommandOptions {
  stdinInput?: string;
  storage?: ProjectStorage;
}

export interface RuntimeCommandResult {
  exitCode: Promise<number>;
  shutdown: () => void;
}

function toMatcherOperations(
  operations: readonly RogatioOperation[],
): MatcherOperation[] {
  return operations.map(({ groupId, ruleId, matcher }) => ({
    kind: "matcher",
    groupId,
    ruleId,
    matcher,
  }));
}

function resolveMockFile(root: string, filePath: string): string | null {
  if (filePath.includes("\0")) return null;
  const absolute = isAbsolute(filePath) ? filePath : resolve(root, filePath);
  const rel = relative(root, absolute);
  if (rel.startsWith("..") || isAbsolute(rel)) return null;
  const logical = rel.split(sep).join("/");
  return logical.length === 0 ? null : logical;
}

function buildMockConfigs(
  operations: readonly RogatioOperation[],
  root: string,
): { ok: true; value: RuntimeMockConfig[] } | { ok: false; message: string } {
  const configs: RuntimeMockConfig[] = [];
  for (const operation of operations) {
    if (operation.kind !== "mock") continue;
    const mock = operation.mock;
    let file: string | undefined;
    if (mock.file !== undefined) {
      const resolved = resolveMockFile(root, mock.file);
      if (resolved === null) {
        return {
          ok: false,
          message: `Mock rule "${operation.ruleId}" file "${mock.file}" resolves outside the configured root (${root}).`,
        };
      }
      file = resolved;
    }
    configs.push({
      ruleId: operation.ruleId,
      status: mock.status,
      ...(mock.headers !== undefined ? { headers: mock.headers } : {}),
      ...(mock.delayMs !== undefined ? { delayMs: mock.delayMs } : {}),
      ...(mock.body !== undefined ? { body: mock.body } : {}),
      ...(file !== undefined ? { file } : {}),
    });
  }
  return { ok: true, value: configs };
}

/**
 * Generate the shell wrapper script that Chrome launches as the native messaging
 * host. The script invokes `rogatio runtime host` without a project path.
 *
 * Chrome provides no arguments to native messaging hosts. The extension sends
 * the project data as the first native message envelope after connectNative(),
 * so the host does not need a project path at launch time.
 */
function generateHostWrapper(rogatioCommand: string, logPath: string): string {
  const parts = rogatioCommand.split(" ");
  const nodeBin = parts[0] ?? "node";
  const cliScript = parts.slice(1).join(" ");
  return `#!/bin/sh
# Rogatio native messaging host wrapper — generated by \`rogatio runtime install\`
# Chrome launches this script when the extension connects via connectNative().
# The extension sends the project data as the first envelope after launch.
# stderr is redirected to a log file for debugging.
exec "${nodeBin}" "${cliScript}" runtime host 2>>"${logPath}"
`;
}

async function writeHostWrapper(
  hostPath: string,
  installRoot: string,
): Promise<void> {
  await mkdir(installRoot, { recursive: true });
  const logPath = join(installRoot, "runtime-host.log");
  const script = generateHostWrapper(
    `${process.execPath} ${process.argv[1] ?? "rogatio"}`,
    logPath,
  );
  await writeFile(hostPath, script, "utf8");
  await chmod(hostPath, 0o755);
}

function makeTrustController() {
  const platform = process.platform;
  const adapter = selectTrustPlatformAdapter(platform);
  const installRoot = defaultTrustInstallRoot(platform);
  return createRequestBodyTrustController({
    platform,
    installRoot,
    hostPath: join(installRoot, "runtime-host"),
    hostName: "com.rogatio.runtime",
    allowedOrigins: [],
    manifestDir: adapter.defaultManifestDir(),
    detectCapabilities: () => adapter.detect(),
    caTrustInstaller: (cert) => adapter.caTrustInstaller(cert),
    caTrustRemover: () => adapter.caTrustRemover(),
  });
}

function reportTrust(
  subcommand: string,
  result: { ok: boolean; state: string; reasons?: readonly string[] },
  okMessage: string,
): number {
  if (result.ok) {
    console.log(okMessage);
    return 0;
  }
  if (result.state === "unsupported") {
    const reasons = result.reasons ?? ["unknown"];
    console.error(`trust unsupported: ${reasons.join(", ")}`);

    // Platform-specific remediation hints
    const hints: Record<string, string> = {
      "tooling-missing":
        "Hint: install required tooling (macOS: security; Linux: update-ca-certificates; Windows: certutil is built-in)",
      "manifest-dir-unwritable":
        "Hint: check permissions on Chrome NativeMessagingHosts directory or run with appropriate access",
      "keychain-unwritable":
        "Hint: macOS login keychain not writable; try running with appropriate keychain access or use sudo for system keychain",
      "ca-store-unwritable":
        "Hint: /usr/local/share/ca-certificates not writable; check directory permissions",
      "elevation-required":
        "Hint: device-local CA trust requires root (Linux: sudo, macOS: keychain password, Windows: Administrator). Re-run with elevated privileges",
    };

    for (const reason of reasons) {
      const hint = hints[reason];
      if (hint) {
        console.error(hint);
      }
    }

    return 1;
  }
  console.error(
    `runtime ${subcommand} failed: ${(result.reasons ?? ["unknown"]).join(", ")}`,
  );
  return 1;
}

async function trustRuntimeCommand(args: string[]): Promise<number> {
  const subcommand = args[0];
  let extensionId: string | undefined;

  if (subcommand === "install") {
    const extIdIndex = args.indexOf("--extension-id");
    if (extIdIndex === -1 || extIdIndex + 1 >= args.length) {
      console.error("Error: --extension-id is required for install command");
      showRuntimeHelp();
      return 2;
    }
    extensionId = args[extIdIndex + 1];

    if (!/^[a-p]{32}$/.test(extensionId)) {
      console.error(
        "Error: --extension-id must be exactly 32 lowercase characters from a through p",
      );
      return 2;
    }
  }

  const controller = makeTrustController();
  const installRoot = defaultTrustInstallRoot(process.platform);
  const hostPath = join(installRoot, "runtime-host");
  switch (subcommand) {
    case "install": {
      const installResult = await controller.install(extensionId ?? "");
      if (installResult.ok) {
        try {
          await writeHostWrapper(hostPath, installRoot);
        } catch (error) {
          console.error(
            `Warning: manifest and CA trusted, but failed to create runtime-host wrapper: ${error instanceof Error ? error.message : String(error)}`,
          );
        }
      }
      return reportTrust(
        "install",
        installResult,
        "runtime install complete: manifest + device-local CA trusted + runtime-host wrapper created\nNote: reload the extension at chrome://extensions for the native host to be detected.",
      );
    }
    case "uninstall": {
      const uninstallResult = await controller.uninstall();
      try {
        await rm(hostPath, { force: true });
      } catch {
        // best-effort wrapper removal
      }
      try {
        await rm(join(installRoot, "runtime-host.log"), { force: true });
      } catch {
        // best-effort log removal
      }
      return reportTrust(
        "uninstall",
        uninstallResult,
        "runtime uninstall complete: manifest + device-local CA removed",
      );
    }
    case "verify": {
      const result = await controller.verify();
      if (result.ok) {
        console.log(
          "runtime verification passed: manifest, binary, and CA trust all OK",
        );
        return 0;
      }
      console.error("runtime verification failed:");
      if (!result.manifestExists) console.error("  manifest not found");
      if (result.manifestExists && !result.manifestValid)
        console.error("  manifest invalid");
      if (!result.binaryExists)
        console.error("  runtime-host binary not found");
      if (result.binaryExists && !result.binaryExecutable)
        console.error("  runtime-host binary not executable");
      if (result.allowedOriginsCount === 0)
        console.error("  no allowed_origins in manifest");
      if (!result.caTrusted) console.error("  device-local CA not trusted");
      for (const reason of result.reasons) {
        if (reason === "manifest-not-found")
          console.error(
            "  Hint: run 'rogatio runtime install --extension-id <id>' to register the host manifest",
          );
        if (reason === "binary-not-found")
          console.error(
            `  Hint: ensure the runtime-host binary exists at the path specified in the manifest`,
          );
        if (reason === "binary-not-executable")
          console.error(
            "  Hint: ensure the runtime-host binary has execute permission (chmod +x)",
          );
        if (reason === "no-allowed-origins")
          console.error(
            "  Hint: re-run 'rogatio runtime install --extension-id <id>' to pin your extension ID",
          );
        if (reason === "ca-not-trusted")
          console.error(
            "  Hint: re-run 'rogatio runtime install --extension-id <id>' with elevated privileges to trust the CA",
          );
      }
      return 1;
    }
    default:
      console.error(`Error: unknown runtime subcommand: ${subcommand ?? ""}`);
      showRuntimeHelp();
      return 2;
  }
}

async function runtimeHostCommand(
  args: string[],
  options: RuntimeCommandOptions = {},
): Promise<number> {
  let root: string | undefined;
  let mockPort: number | undefined;
  const positional: string[] = [];
  let argumentError: string | undefined;

  for (let index = 0; index < args.length; index += 1) {
    const arg = args[index];
    if (arg === "--root" && index + 1 < args.length) {
      root = resolve(args[++index]);
    } else if (arg === "--root") {
      argumentError = "--root requires a value";
    } else if (arg === "--mock-port" && index + 1 < args.length) {
      const parsed = Number(args[++index]);
      if (!Number.isInteger(parsed) || parsed <= 0 || parsed > 65535) {
        argumentError = "--mock-port must be an integer port in 1..65535";
      } else {
        mockPort = parsed;
      }
    } else if (arg === "--mock-port") {
      argumentError = "--mock-port requires a value";
    } else if (arg === "-" || !arg.startsWith("-")) {
      positional.push(arg);
    } else {
      argumentError = `Unknown option: ${arg}`;
    }
  }

  if (argumentError) {
    console.error(`Error: ${argumentError}`);
    return 2;
  }

  const inputPath = positional[0];

  // Deferred mode: no project path provided, wait for runtime.project.set envelope
  if (!inputPath) {
    const aiProviderConfig = await readProviderConfig();
    await runNativeHost({
      fileRoot: root,
      ...(mockPort !== undefined ? { mockPort } : {}),
      ...(aiProviderConfig !== null ? { aiProviderConfig } : {}),
      onReady: () =>
        console.error(
          "rogatio runtime-host active (deferred, waiting for project)",
        ),
    });
    return 0;
  }

  // Explicit project path mode: validate, compile, build preset, run host
  let filePath: string;
  let projectData: unknown;
  const storage = options.storage ?? createJsonFileProjectStorage();
  try {
    if (inputPath === "-") {
      const chunks: string[] = [];
      for await (const chunk of process.stdin) {
        chunks.push(typeof chunk === "string" ? chunk : chunk.toString("utf8"));
      }
      filePath = "<stdin>";
      projectData = JSON.parse(chunks.join(""));
    } else {
      filePath = resolve(inputPath);
      projectData = await storage.get(filePath);
    }
  } catch (error) {
    const message = error instanceof Error ? error.message : "Unknown error";
    console.error(`Error: ${message}`);
    return 2;
  }

  const schemaResult = validateProjectDetailed(projectData);
  if (!schemaResult.valid) {
    for (const issue of schemaResult.errors) {
      console.error(
        `${issue.instancePath || "/"}/: ${issue.message} (schema.${issue.keyword})`,
      );
    }
    return 1;
  }
  const compileResult = compileProject(schemaResult.data);
  if (!compileResult.ok) {
    for (const diagnostic of compileResult.diagnostics) {
      console.error(
        `${diagnostic.path}: ${diagnostic.message} (${diagnostic.code})`,
      );
    }
    return 1;
  }

  const rootDir =
    root ?? (inputPath === "-" ? process.cwd() : dirname(filePath));
  const mocksResult = buildMockConfigs(compileResult.operations, rootDir);
  if (!mocksResult.ok) {
    console.error(`Error: ${mocksResult.message}`);
    return 1;
  }

  const normalized = normalizeRuntimePreset({
    version: 1,
    limits: RUNTIME_LIMITS,
    matchers: toMatcherOperations(compileResult.operations),
    grants: [],
    ...(mocksResult.value.length > 0 ? { mocks: mocksResult.value } : {}),
  });
  if (!normalized.ok) {
    console.error("Error: Failed to build runtime preset");
    return 2;
  }

  const aiProviderConfig = await readProviderConfig();
  await runNativeHost({
    preset: normalized.value,
    fileRoot: rootDir,
    ...(mockPort !== undefined ? { mockPort } : {}),
    ...(aiProviderConfig !== null ? { aiProviderConfig } : {}),
    onReady: () => console.error("rogatio runtime-host active"),
  });
  return 0;
}

export function runtimeCommand(
  args: ["install" | "uninstall" | "host", ...string[]],
  options?: RuntimeCommandOptions,
): Promise<number>;
export function runtimeCommand(
  args: ["--help" | "-h", ...string[]],
  options?: RuntimeCommandOptions,
): Promise<number>;
export function runtimeCommand(
  args: [string, ...string[]],
  options?: RuntimeCommandOptions,
): Promise<number | RuntimeCommandResult>;
export function runtimeCommand(
  args: string[],
  options?: RuntimeCommandOptions,
): Promise<number | RuntimeCommandResult>;

export async function runtimeCommand(
  args: string[],
  options: RuntimeCommandOptions = {},
): Promise<number | RuntimeCommandResult> {
  if (args.includes("--help") || args.includes("-h")) {
    showRuntimeHelp();
    return 0;
  }

  const first = args[0];
  if (
    first === "install" ||
    first === "trust" ||
    first === "uninstall" ||
    first === "verify"
  )
    return trustRuntimeCommand(args);
  if (first === "host") return runtimeHostCommand(args.slice(1), options);

  console.error(
    `Error: 'rogatio runtime' no longer starts or stops the runtime. Use 'rogatio runtime install|uninstall' to manage the host manifest and request-body trust, or 'rogatio runtime host [path]' to run the native-messaging host. Start/stop is driven from the extension's controls.`,
  );
  showRuntimeHelp();
  return 2;
}

/**
 * Native-messaging host entry point. The browser launches the manifest's
 * `runtime-host` executable directly (no subcommand); this routes the process
 * to the runtime host, reading the project from the conventional path.
 */
export async function runRuntimeHostEntry(): Promise<void> {
  const code = await runtimeHostCommand(process.argv.slice(2));
  process.exitCode = code;
}
